
Scikit-Learn 맛보기
Iris 분류 - 결정 트리(Decision Tree)


1.데이터 전처리, 탐색

In [ ]:
import sklearn
sklearn.__version__

'1.2.2'

In [ ]:
from sklearn.datasets import load_iris
iris =load_iris()

In [ ]:
# iris 데이터를 액세스하는 방법
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
#data -X (sl, sw, pl,pw)
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
# feature_names -X 값의 이름
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
#  target - y
iris.target[:5]

array([0, 0, 0, 0, 0])

In [ ]:
#  target_names -y 의 이름
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
import pandas as pd
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['species']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [ ]:
#  X, y의 shape
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [ ]:
#  y 값의 분포
df.species.value_counts()

0    50
1    50
2    50
Name: species, dtype: int64

In [ ]:
# DESCR- 설명 (description)
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
#   기초 통계자료
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

2. 학습데이터와  테스트 데이터로 분리

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
# X - 2차원이라서 대문자로 표기, y - 1차원이라 소문자로 표기
# train : test = 3:1( test_size = 0.25가 디폴트)
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=2023)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [ ]:
#  y_train 값의 분포
np.unique(y_train, return_counts = True)

(array([0, 1, 2]), array([34, 37, 41]))

In [ ]:
#  y 값의 분포를 균일하게
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state =2023, stratify=iris.target, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [ ]:
#  학습 데이터와 테스트 데이터의 비율(test_size)
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=2023, stratify=iris.target, test_size =0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [ ]:
np.unique(y_train, return_counts =True)

(array([0, 1, 2]), array([40, 40, 40]))

3. 학습(훈련, train)

In [ ]:
#  결정트리모델
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#  모델 생성,- 객체 생성
dtc = DecisionTreeClassifier()

In [ ]:
# 하이퍼 파라미터
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [ ]:
#  학습(훈련)실행
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

4. 예측(Prediction)

In [ ]:
#  X_test 값을 주고 예측값을 반환 받음
pred = dtc.predict(X_test)

In [ ]:
rf = pd.DataFrame({'y 실제값': y_test, 'y 예측값': pred})
rf.head()

y 실제값  y 예측값
0      2      2
1      0      0
2      1      1
3      1      1
4      0      0

In [ ]:
X_test[:5]

array([[6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 2.5, 3. , 1.1],
       [5.9, 3. , 4.2, 1.5],
       [4.6, 3.6, 1. , 0.2]])

5.평가(Evaluation)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9666666666666667

In [ ]:
#  4,5 과정을 한번에
dtc.score(X_test, y_test)

0.9666666666666667